### ISSUE TITLE
Pressing enter in another input will open color picker

### ISSUE THREAD

**Issue by maximecolin** [thednp/color-picker#1]
Hi.

Just trying your color picker and I encountered the following bug:

When I focus another input than the color picker input and press Enter, it open/close the color picker instead of submitting the form (default behavior). I believe your lib catch all key events instead of listening only key press in the color picker input.

Here is a reproduction code: https://jsfiddle.net/ehgjm5zt/1/

**Comment by thednp** [comment]
Thank you. WIll have a look and fix as soon as I can.

**Comment by thednp** [comment]
Found the fix, [it was easy](https://stackoverflow.com/questions/73484680/pressing-enter-key-on-input-field-triggers-button-click-function). Will update the code as soon as I get some time, there are other inner working need updated.

**Comment by thednp** [comment]
@maximecolin new version published.

Thank you for reporting.
