### ISSUE TITLE
How to return value if color has been changed?

### ISSUE THREAD

**Issue by victordobryi** [thednp/color-picker#4]
const colorPic = new ColorPicker('#colorPic ');
Can I directly access and call a method that would return the color to me

**Comment by thednp** [comment]
colorPick.color is the Color object, with it's own methods: toString, toRgb..

**Comment by victordobryi** [comment]
how do I get the value back when the color changes.
For example:   colorPic.addEventListener('change', (color) => console.log(color))

**Comment by thednp** [comment]
Sorry I didn't understand what you need, I've updated the [Wiki](https://github.com/thednp/color-picker/wiki/API#colorpicker-custom-event) hope this helps.
